-- 7天签到任务
return {
	[1] = {
		taskName = "斗地主对局2局",
		rewardName = "1元红包券",
		taskType = 4,
		bActive = false,
		gameType = 1,
		bMatch = true,
		rewardType = 7,
		reWardCount = 10,
		iFhishJushu = 2,
		iCurFinshJushu = 0,
		rewardImg = "img2/loginWelfare/daoju/hongbao.png",
	},
	[2] = {
		taskName = "任意游戏5局",
		rewardName = "钥匙x1",
		taskType = 4,
		bActive = false,
		gameType = 0,
		bMatch = false,
		rewardType = 8,
		reWardCount = 1,
		iFhishJushu = 5,
		iCurFinshJushu = 0,
		rewardImg = "img2/loginWelfare/daoju/yaoshi.png",
	},
	[3] = {
		taskName = "完成一场斗地主比赛",
		rewardName = "钥匙x1",
		taskType = 9,
		bActive = false,
		gameType = 1,
		bMatch = false,
		rewardType = 8,
		reWardCount = 1,
		iFhishJushu = 1,
		iCurFinshJushu = 0,
		rewardImg = "img2/loginWelfare/daoju/yaoshi.png",
	},
	[4] = {
		taskName = "邀请一个好友（注册并登录）",
		rewardName = "1元红包券",
		taskType = 10,
		bActive = false,
		gameType = 0,
		bMatch = false,
		rewardType = 7,
		reWardCount = 10,
		iFhishJushu = 1,
		iCurFinshJushu = 0,
		rewardImg = "img2/loginWelfare/daoju/hongbao.png",
	},
	[5] = {
		taskName = "欢乐拼十获胜10局",
		rewardName = "20000金币",
		taskType = 6,
		bActive = false,
		gameType = 5,
		bMatch = false,
		rewardType = 1,
		reWardCount = 20000,
		iFhishJushu = 10,
		iCurFinshJushu = 0,
		rewardImg = "img2/loginWelfare/daoju/jinbi.png",
	},
	[6] = {
		taskName = "充值任意金额（至少6元）",
		rewardName = "周卡",
		taskType = 7,
		bActive = false,
		gameType = 0,
		bMatch = false,
		rewardType = 9,
		reWardCount = 1,
		iFhishJushu = 1,
		iCurFinshJushu = 0,
		rewardImg = "img2/loginWelfare/daoju/zhouka.png",
	},
	[7] = {
		taskName = "累计签到七次",
		rewardName = "10元红包券",
		taskType = 8,
		bActive = false,
		gameType = 0,
		bMatch = false,
		rewardType = 7,
		reWardCount = 100,
		iFhishJushu = 7,
		iCurFinshJushu = 0,
		rewardImg = "img2/loginWelfare/daoju/hongbao.png",
	},
}
