
return {
	[1] = {
		name = "三局比赛场",
		gold1 = 30,
		gold2 = 0,
		num1 = 6,
		num2 = 3,
		maxBet = 12,
		iRoomLevel = 1,
		iAllInnings = 3,
		registration = 6,
		desc = "每三局奖励钥匙：1",
		background = "img2/grabredlords/game_bg_2.jpg",
		title = "img2/grabredlords/sanjubishai.png",
	},
	[2] = {
		name = "单局决赛场",
		gold1 = 78,
		gold2 = 0,
		num1 = 6,
		num2 = 9,
		maxBet = 36,
		iRoomLevel = 2,
		iAllInnings = 1,
		registration = 6,
		desc = "每局奖励钥匙：5、2、1",
		background = "img2/grabredlords/game_bg.jpg",
		title = "img2/grabredlords/danjujueshai.png",
	},
	[3] = {
		name = "单局王者场",
		gold1 = 132,
		gold2 = 0,
		num1 = 6,
		num2 = 15,
		maxBet = 60,
		iRoomLevel = 3,
		iAllInnings = 1,
		registration = 12,
		desc = "每局奖励钥匙：10、5、2",
		background = "img2/grabredlords/game_bg_1.jpg",
		title = "img2/grabredlords/danjuwangzhe.png",
	},
}
