-- ID                               int                              道具ID
-- classify                         int                              道具类型，1为金币，2为钻石，3为道具，4为月卡,5快购，6门票,7首充
-- name                             string                           道具名称
-- gongneng                         string                           道具功能
-- time                             int                              有效期限（天） 0为不限
-- picture                          string                           道具图标ID

return {
	[101] = {
		classify = 1,
		name = "3万",
		gongneng = "购买后获得3万金币",
		time = 0,
		picture = "jinbi1.png",
	},
	[102] = {
		classify = 1,
		name = "5万",
		gongneng = "购买后获得5万金币",
		time = 0,
		picture = "jinbi2.png",
	},
	[103] = {
		classify = 1,
		name = "10万",
		gongneng = "购买后获得10万金币",
		time = 0,
		picture = "jinbi3.png",
	},
	[104] = {
		classify = 1,
		name = "50万",
		gongneng = "购买后获得50万金币",
		time = 0,
		picture = "jinbi4.png",
	},
	[105] = {
		classify = 1,
		name = "110万",
		gongneng = "购买后获得110万金币",
		time = 0,
		picture = "jinbi5.png",
	},
	[106] = {
		classify = 1,
		name = "240万",
		gongneng = "购买后获得240万金币",
		time = 0,
		picture = "jinbi6.png",
	},
	[201] = {
		classify = 2,
		name = "60钻",
		gongneng = "购买后获得60钻石",
		time = 0,
		picture = "zuanshi1.png",
	},
	[202] = {
		classify = 2,
		name = "120钻",
		gongneng = "购买后获得120钻石",
		time = 0,
		picture = "zuanshi2.png",
	},
	[203] = {
		classify = 2,
		name = "200钻",
		gongneng = "购买后获得200钻石",
		time = 0,
		picture = "zuanshi3.png",
	},
	[204] = {
		classify = 2,
		name = "680钻",
		gongneng = "购买后获得680钻石",
		time = 0,
		picture = "zuanshi4.png",
	},
	[205] = {
		classify = 2,
		name = "1280钻",
		gongneng = "购买后获得1280钻石",
		time = 0,
		picture = "zuanshi5.png",
	},
	[206] = {
		classify = 2,
		name = "2980钻",
		gongneng = "购买后获得2980钻石",
		time = 0,
		picture = "zuanshi6.png",
	},
	[207] = {
		classify = 2,
		name = "9980钻",
		gongneng = "购买后获得9980钻石",
		time = 0,
		picture = "zuanshi7.png",
	},
	[208] = {
		classify = 2,
		name = "60钻",
		gongneng = "购买后获得60钻石",
		time = 0,
		picture = "zuanshi1.png",
	},
	[209] = {
		classify = 2,
		name = "120钻",
		gongneng = "购买后获得120钻石",
		time = 0,
		picture = "zuanshi2.png",
	},
	[210] = {
		classify = 2,
		name = "680钻",
		gongneng = "购买后获得680钻石",
		time = 0,
		picture = "zuanshi4.png",
	},
	[211] = {
		classify = 2,
		name = "1280钻",
		gongneng = "购买后获得1280钻石",
		time = 0,
		picture = "zuanshi5.png",
	},
	[212] = {
		classify = 2,
		name = "2980钻",
		gongneng = "购买后获得2980钻石",
		time = 0,
		picture = "zuanshi6.png",
	},
	[213] = {
		classify = 2,
		name = "6480钻",
		gongneng = "购买后获得6480钻石",
		time = 0,
		picture = "zuanshi7.png",
	},
	[214] = {
		classify = 2,
		name = "9980钻",
		gongneng = "购买后获得9980钻石",
		time = 0,
		picture = "zuanshi7.png",
	},
	[301] = {
		classify = 3,
		name = "记牌器",
		gongneng = "统计当前牌局尚未出现的牌",
		time = 0,
		picture = "jpq.png",
	},
	[303] = {
		classify = 3,
		name = "飞吻",
		gongneng = "游戏中点击对方头像，对其它玩家使用",
		time = 0,
		picture = "fw.png",
	},
	[304] = {
		classify = 3,
		name = "西红柿",
		gongneng = "游戏中点击对方头像，对其它玩家使用",
		time = 0,
		picture = "fq.png",
	},
	[305] = {
		classify = 3,
		name = "鸡蛋",
		gongneng = "游戏中点击对方头像，对其它玩家使用",
		time = 0,
		picture = "jd.png",
	},
	[306] = {
		classify = 3,
		name = "鲜花",
		gongneng = "游戏中点击对方头像，对其它玩家使用",
		time = 0,
		picture = "mg.png",
	},
	[307] = {
		classify = 3,
		name = "福袋",
		gongneng = "每次发送广场红包时消耗",
		time = 0,
		picture = "fd.png",
	},
	[308] = {
		classify = 3,
		name = "喇叭",
		gongneng = "每次发送广播时消耗",
		time = 0,
		picture = "lb.png",
	},
	[309] = {
		classify = 3,
		name = "钥匙",
		gongneng = "幸运转盘消耗",
		time = 0,
		picture = "yaoshi/10.png",
	},
	[401] = {
		classify = 4,
		name = "至尊周卡",
		gongneng = "获得低级VIP特权",
		time = 7,
		picture = "market_vip_week.png",
	},
	[402] = {
		classify = 4,
		name = "至尊周卡",
		gongneng = "获得低级VIP特权",
		time = 7,
		picture = "market_vip_week.png",
	},
	[403] = {
		classify = 4,
		name = "至尊月卡",
		gongneng = "获得高级VIP特权",
		time = 30,
		picture = "market_vip_month.png",
	},
	[501] = {
		classify = 5,
		name = "12万",
		gongneng = "购买后获得12万金币",
		time = 0,
		picture = "jinbi3.png",
	},
	[502] = {
		classify = 5,
		name = "98万",
		gongneng = "购买后获得98万金币",
		time = 0,
		picture = "jinbi5.png",
	},
	[503] = {
		classify = 5,
		name = "998万",
		gongneng = "购买后获得998万金币",
		time = 0,
		picture = "jinbi6.png",
	},
	[504] = {
		classify = 5,
		name = "648万",
		gongneng = "购买后获得648万金币",
		time = 0,
		picture = "jinbi6.png",
	},
	-- [FIRST_CHARGE_ID] = {
	-- 	classify = 6,
	-- 	name = "33门票加2万金币",
	-- 	gongneng = "购买后获得33门票加2万金币",
	-- 	time = 0,
	-- 	picture = "menpiao1.png",
	-- },
	[601] = {
		classify = 6,
		name = "30门票",
		gongneng = "购买后获得30门票",
		time = 0,
		picture = "menpiao1.png",
	},
	[602] = {
		classify = 6,
		name = "300门票",
		gongneng = "购买后获得300门票",
		time = 0,
		picture = "menpiao2.png",
	},
	[603] = {
		classify = 6,
		name = "600门票",
		gongneng = "购买后获得600门票",
		time = 0,
		picture = "menpiao3.png",
	},
	[604] = {
		classify = 6,
		name = "1800门票",
		gongneng = "购买后获得1800门票",
		time = 0,
		picture = "menpiao4.png",
	},
	[605] = {
		classify = 6,
		name = "30门票",
		gongneng = "购买后获得30门票",
		time = 0,
		picture = "menpiao1.png",
	},
	[606] = {
		classify = 6,
		name = "60门票",
		gongneng = "购买后获得60门票",
		time = 0,
		picture = "menpiao2.png",
	},
	[701] = {
		classify = 7,
		name = "6元大礼包",
		gongneng = "购买后获得33门票+2万金币",
		time = 0,
		picture = "menpiao3.png",
	},
	[702] = {
		classify = 7,
		name = "28元大礼包",
		gongneng = "购买后获得145门票+8万金币",
		time = 0,
		picture = "menpiao3.png",
	},
	[703] = {
		classify = 7,
		name = "88元大礼包",
		gongneng = "购买后获得450门票+20万金币",
		time = 0,
		picture = "menpiao3.png",
	},
	[704] = {
		classify = 7,
		name = "168元大礼包",
		gongneng = "购买后获得860门票+30万金币",
		time = 0,
		picture = "menpiao4.png",
	},
	[705] = {
		classify = 7,
		name = "388元大礼包",
		gongneng = "购买后获得2000门票+50万金币",
		time = 0,
		picture = "menpiao4.png",
	},
	[801] = {
		classify = 8,
		name = "1元复活",
		gongneng = "1元复活门票恢复30",
		time = 0,
		picture = "menpiao1.png",
	},
	[802] = {
		classify = 8,
		name = "2元复活",
		gongneng = "2元复活门票恢复30",
		time = 0,
		picture = "menpiao1.png",
	},
}
