-- ID                               int                              vipID
-- LV                               int                              VIP等级
-- privilege                        int                              红名特权，不开通0，开通为1
-- snidel                           int                              每日领取福袋数量
-- Receive                          int                              每日领取大喇叭数量
-- Num                              int                              红包广场同时挂出红包数量
-- privilege2                       int                              VIP头像框特权，不开通0，开通为1
-- frequency                        int                              破产补助总领取次数
-- Gold                             int                              破产补助每次领取金币数
-- lottery                       int                              微信红包总兑换次数
-- mon                              int                              需充值金额
-- display                          string                           商城特权显示
-- picture                          string                           头像框图片

return {
	[1] = {
		LV = 1,
		privilege = 1,
		snidel = 0,
		Receive = 0,
		Num = 0,
		privilege2 = 1,
		frequency = 0,
		Gold = 0,
		lottery = 20,
		mon = 20,
		display = "1.VIP专属红名特权\n2.VIP1专属尊贵头像边框\n3.每日签到多送2000金币\n4.幸运转盘每日抽奖次数上限20",
		picture = "LV1.png",
	},
	[2] = {
		LV = 2,
		privilege = 1,
		snidel = 5,
		Receive = 0,
		Num = 2,
		privilege2 = 1,
		frequency = 0,
		Gold = 0,
		lottery = 50,
		mon = 100,
		display = "1.VIP专属红名特权\n2.VIP2专属尊贵头像边框\n3.每日签到多送2800金币\n4.幸运转盘每日抽奖次数上限50",
		picture = "LV2.png",
	},
	[3] = {
		LV = 3,
		privilege = 1,
		snidel = 10,
		Receive = 0,
		Num = 3,
		privilege2 = 1,
		frequency = 0,
		Gold = 0,
		lottery = 80,
		mon = 400,
		display = "1.VIP专属红名特权\n2.VIP3专属尊贵头像边框\n3.每日签到多送3800金币\n4.幸运转盘每日抽奖次数上限80",
		picture = "LV3.png",
	},
	[4] = {
		LV = 4,
		privilege = 1,
		snidel = 20,
		Receive = 0,
		Num = 5,
		privilege2 = 1,
		frequency = 0,
		Gold = 0,
		lottery = 120,
		mon = 900,
		display = "1.VIP专属红名特权\n2.VIP4专属尊贵头像边框\n3.每日签到多送5800金币\n4.幸运转盘每日抽奖次数上限120",
		picture = "LV4.png",
	},
	[5] = {
		LV = 5,
		privilege = 1,
		snidel = 30,
		Receive = 0,
		Num = 5,
		privilege2 = 1,
		frequency = 0,
		Gold = 0,
		lottery = 200,
		mon = 1900,
		display = "1.VIP专属红名特权\n2.VIP5专属尊贵头像边框\n3.每日签到多送8800金币\n4.幸运转盘每日抽奖次数上限200",
		picture = "LV5.png",
	},
	[6] = {
		LV = 6,
		privilege = 1,
		snidel = 50,
		Receive = 0,
		Num = 5,
		privilege2 = 1,
		frequency = 0,
		Gold = 0,
		lottery = 300,
		mon = 4900,
		display = "1.VIP专属红名特权\n2.VIP6专属尊贵头像边框\n3.每日签到多送12800金币\n4.幸运转盘每日抽奖次数上限300",
		picture = "LV6.png",
	},
	[7] = {
		LV = 7,
		privilege = 1,
		snidel = 50,
		Receive = 1,
		Num = 5,
		privilege2 = 1,
		frequency = 0,
		Gold = 0,
		lottery = 500,
		mon = 9900,
		display = "1.VIP专属红名特权\n2.VIP7专属尊贵头像边框\n3.每日签到多送22800金币\n4.幸运转盘每日抽奖次数上限500",
		picture = "LV7.png",
	},
	[8] = {
		LV = 8,
		privilege = 1,
		snidel = 50,
		Receive = 5,
		Num = 5,
		privilege2 = 1,
		frequency = 0,
		Gold = 0,
		lottery = 800,
		mon = 19900,
		display = "1.VIP专属红名特权\n2.VIP8专属尊贵头像边框\n3.每日签到多送38000金币\n4.幸运转盘每日抽奖次数上限800",
		picture = "LV8.png",
	},
	[9] = {
		LV = 9,
		privilege = 1,
		snidel = 50,
		Receive = 10,
		Num = 5,
		privilege2 = 1,
		frequency = 0,
		Gold = 0,
		lottery = 1000,
		mon = 50000,
		display = "11.VIP专属红名特权\n2.VIP9专属尊贵头像边框\n3.每日签到多送50000金币\n4.幸运转盘每日抽奖次数上限1000",
		picture = "LV9.png",
	},
	[10] = {
		LV = 10,
		privilege = 1,
		snidel = 50,
		Receive = 30,
		Num = 5,
		privilege2 = 1,
		frequency = 0,
		Gold = 0,
		lottery = 1200,
		mon = 99000,
		display = "1.VIP专属红名特权\n2.皇冠VIP专属尊贵头像边框\n3.每日签到多送88000金币\n4.幸运转盘每日抽奖次数上限1200",
		picture = "LV10.png",
	},
}
